/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   utils.c                                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: von <von@student.42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/05/07 15:15:18 by tseche            #+#    #+#             */
/*   Updated: 2026/05/22 01:33:40 by von              ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../includes/bonus.h"

bool	had_space_neighbour(t_map_simu *map, int x, size_t y)
{
	const int dx[] = {-1, -1, -1, 0, 0, 1, 1, 1};
    const int dy[] = {-1, 0, 1, -1, 1, -1, 0, 1};
	
    for (int i = 0; i < 8; i++) {
        int nx = x + dx[i];
        int ny = y + dy[i];

        // Check if the neighbor is within grid boundaries
        if (nx >= 0 && nx < map->height && ny >= 0 && ny < map->width)
		{
			// printf("x:%d, y:%d, height:%d, width:%d\n", nx, ny, map->height, map->width);
			if (map->map[nx][ny] == ' ')
            	return (true);
        }
	}
	return (false);
}

bool    map_empty(t_map_simu *map)
{
	int	i;
	int	j;

	i = 0;
	while (i <= map->height){
		j = 0;
		j += skip_spaces(map->map[i]);
		if (j != map->width)
			return (false);
		i++;
	}
	return (true);
}

static inline char	**get_error_bns()
{
	static	const	char	*err[ERROR_MAX_BNS] = {
		("The map generated by the produral generation"
		" result in a empty map"),
		("No spawn point has been found on the map")
	};
	return ((char **)err);
}

void	throw_error_bonus(int err)
{
	char	**msg;
	err = abs(err);
	printf("ERROR:\n");
	if (err <= ERROR_MAX_BNS)
	{
		msg = get_error_bns();
		printf("%s\n", msg[err]);
	}
	else
	{
		printf("Unknown error thrown in bonus\n");
	}
}

int	add_digit_number(long int nb)
{
	int	sum;

	sum = 0;
	while (nb > 9)
	{
		sum += nb % 10;
		nb /= 10;
	}
	sum += nb % 10;
	return (sum);
}
