/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   utils_gen_bonus.c                                  :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: tseche <tseche@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/05/07 15:15:18 by tseche            #+#    #+#             */
/*   Updated: 2026/06/15 15:12:31 by tseche           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../includes/bonus.h"

bool	had_space_neighbour(t_map_simu *map, int x, size_t y)
{
	const int	dx[] = {-1, -1, -1, 0, 0, 1, 1, 1};
	const int	dy[] = {-1, 0, 1, -1, 1, -1, 0, 1};
	int			i;
	int			nx;
	int			ny;

	i = 0;
	while (i < 8)
	{
		nx = x + dx[i];
		ny = y + dy[i];
		if (nx >= 0 && nx < map->height && ny >= 0 && ny < map->width)
		{
			if (map->map[nx][ny] == ' ')
				return (true);
		}
		i++;
	}
	return (false);
}

bool	map_empty(t_map_simu *map)
{
	int	i;
	int	j;

	i = 0;
	while (i <= map->height)
	{
		j = 0;
		j += skip_spaces(map->map[i]);
		if (j != map->width && map->map[i])
			return (false);
		i++;
	}
	return (true);
}

static inline char	**get_error_bns(void)
{
	static const char	*err[ERROR_MAX_BNS] = {
		("The argument provided is unknown\n"),
		("The provided seed is invalid\n"),
		("The map generated by the produral generation"
			" result in a empty map\n"),
		("No spawn point has been found on the map\n"),
		("Malloc error allocation in the procedural generation\n")
	};

	return ((char **)err);
}

void	throw_error_bonus(int err)
{
	char	**msg;

	err = abs(err);
	ft_putstr_fd("ERROR:\n", 2);
	if (err <= ERROR_MAX_BNS)
	{
		msg = get_error_bns();
		ft_putstr_fd(msg[err], 2);
	}
	else
		ft_putstr_fd("Unknown error thrown in bonus\n", 2);
}

int	add_digit_number(long int nb)
{
	int	sum;

	sum = 0;
	while (nb > 9)
	{
		sum += nb % 10;
		nb /= 10;
	}
	sum += nb % 10;
	return (sum);
}
